const Top_categories=[
    { id:1,category:"Anarkali",images:require('./Images/anarkali.jpg'),name:'Anarkali'},
    { id:2,category:"PattuSaree",images:require('./Images/Pattu Saree.jpg'),name:'Pattu Saree'},
    { id:3,category:"Saree",images:require('./Images/Sarees.jpg'),name:'Sarees'},
    { id:4,category:"Anarkali_Serwani",images:require('./Images/anarkali serwani.jpg'),name:'Anarkali Serwani'},
    { id:5,category:"Dhorti_Serwani",images:require('./Images/Dhoti serwani.jpg'),name:'Dhoti Serwani'},
    { id:6,category:"Jodhpuri_Suits",images:require('./Images/Jodhpuri Suits.jpg'),name:'Jodhpuri Suit'},
    { id:7,category:"Kurta",images:require('./Images/Kurta.jpg'),name:'Kurta'},
    { id:8,category:"Serwani",images:require('./Images/Sherwani.jpg'),name:'Sherwani'},

]
const Bride_collections=[
    {  id:1,   image:'https://drive.google.com/uc?export=view&id=1L-v7s6YLj_4e3qKhZHP_SX6jugbsCdGr', category:"Ananrkali",  name:'Stunning heavy Embroider Pink Anarkali Gown',  price:'29,999'},
    {  id:2,   image:'https://drive.google.com/uc?export=view&id=1j1iuAkEbPoa53v3qhZudXv3udlcwOyAp', category:"Anarkali",   name:'Stunning Red Anarkali Gown',  price:'25,500'},
    {  id:3,   image:'https://drive.google.com/uc?export=view&id=1d-ftuCqbN29eKdeOdti0aCON850e5m0I', category:"Anarkali",   name:'Maroon Anarkali suits with Heavy Embroidery Gown',  price:'40,000 '},
    {  id:4,   image:'https://drive.google.com/uc?export=view&id=1oB7K0Ik9ZkbVaWCwPgV0hRpypRAaj3w_', category:"Pattu Saree",name:'Yellow Pattu Saree',  price:'5000 '},
    {  id:5,   image:'https://drive.google.com/uc?export=view&id=19NGFTtvIBRx5vtUCDkoYwRIqU6xT1oRv', category:"Anarkali",   name:'Flowers Embroidery with Anarkali Gown', rice:'23,000' },
    {  id:6,   image:'https://drive.google.com/uc?export=view&id=1xerR9lmNaAfkz42fEPGXt9S8gx-q-VaX', category:"Saree",      name:'Purple with Gold Slik Saree',  price:'7500 '},
    {  id:7,   image:'https://drive.google.com/uc?export=view&id=1F8wVioqMUhh6hph4_P7zi4bEElN1diJc', category:"Anarkali",   name:'Green Anarkali Gown for Bride  Wedding',price:'24,000'},
    {  id:8,   image:'https://drive.google.com/uc?export=view&id=1O4EqlHfNn-vIN0_YRqvLbMg7sVQ2LdJH', category:"Saree",      name:'Red Slik Saree',  price:'8650'},
    {  id:9,   image:'https://drive.google.com/uc?export=view&id=1oZCGR97QO2bkt_5oaU7JV1vya6rgg-Z5', category:"Pattu Saree",name:'Parrot Green Pattu Saree',  price:'4950'},
    {  id:10,  image:'https://drive.google.com/uc?export=view&id=1bEk7KyNFMnEJ0K0joNFbk-RiWs3rA1--', category:"Saree",      name:"Women's Art Slik Saree", price:'12,500    '},
]
const  Shoe_collections=[
    { id:1, image:'https://drive.google.com/uc?export=view&id=1-hkEq37PhBIMGjIy1VPpCRQ9hl1CSO0x',   name:'Brown Wedding Elevator Shoes for Groom  ', price:'3500'},
    { id:2, image:'https://drive.google.com/uc?export=view&id=1sqTiLeuhfeC2DtfW4w2Ez1rnhsEszhXo',   name:'Mojadi Shewani Shoes for Wedding Groom', price:'2500'},
    { id:3, image:'https://drive.google.com/uc?export=view&id=17kx8VaHJJY-OlOr_nc7MGk6LBmJekiGT',   name:'New Handmade Pure leather shoes',  price:'1599'},
    { id:4, image:'https://drive.google.com/uc?export=view&id=16QMrUkId4-LyPS8y78r__5s8vWQGHCyP',   name:'Mojadi Shewani Shoes for Wedding Groom ',  price:'2599'},
    { id:5, image:'https://drive.google.com/uc?export=view&id=1EmYtGUyfbsFJEoZnkjkLbm4xirUXVq06',   name:'Maroon with stones Embroided Shewani Shoes for Wedding Groom',  price:'4500'},
    { id:6, image:'https://drive.google.com/uc?export=view&id=1fVU2N2WjlSzy7R5mOZuM6SRnDTaR3XtF',   name:'Brown Pure leather shoes',  price:'1450' },
    { id:7, image:'https://drive.google.com/uc?export=view&id=1BG3UinMG-gc6q2FsdPGR4K-vVz_VUu-W',   name:'Handmade Shewani Shoes with Embroideing works',  price:'3950'},
    { id:8, image:'https://drive.google.com/uc?export=view&id=1kplHUraol0BNfgpKtRI2YIb5MTJL1s55',   name:'Golden Ltalian Leather Party Shoes ',  price:'1750'}, 
    { id:9, image:'https://drive.google.com/uc?export=view&id=14T9JcXpYo-9HE_GK9_GlPiYWIKxPG8CL',   name:'Leather Shewani Shoes',  price:'4050'}, 
    { id:10,image:'https://drive.google.com/uc?export=view&id=1-uMs9E1Db5EyZB6QOi1yAbN6r47ZciYF',   name:'Dark Blue Sherwani Shoes for Groom',  price:'3500'}, 
    { id:11,image:'https://drive.google.com/uc?export=view&id=1A1_NIkkH8yRAjRdUm0fBHZFObt6Uv2zO',   name:'New Borough',  price:'2500'},
    { id:12,image:'https://drive.google.com/uc?export=view&id=1SzBJwkoCkHMbgaar5F7xbX1cZFJfwapl',   name:'Mcclean',  price:'2000'},
    { id:13,image:'https://drive.google.com/uc?export=view&id=1QaCGlW40X8fYYow0ev2x2vshVwf-9ipG',   name:'Loafers',  price:'1599'}, 
  
] 
const Groom_collections=[ 
    { id:1,image:'https://drive.google.com/uc?export=view&id=1PUGcwGh5IBW66UNrziElXx-cqJ2Zq5qv',category:"Jodhpuri Suits",name:'Pure Black Jodhpuri Suit', price:'7999'},
    { id:2,image:'https://drive.google.com/uc?export=view&id=1yuWIvIw1EDExHA9_UbQH6jDMNRY7jIIf',category:"Serwani",name:'Pearl White with Semi Indo Western Serwani',price:'21,590'},    
    { id:3,image:'https://drive.google.com/uc?export=view&id=1pLo6YtKy8OCHw91BO1SY1DunIhKKbx23',category:"Anarkali Serwani", name:'Pink Slik Anarkali Serwani',price:'14,500'},      
    { id:4,image:'https://drive.google.com/uc?export=view&id=1R4vL36VCZSVDJHlASvU1Jnxd7i4ByeGF',category:"Anarkali Serwani",  name:'Slik Anarkali serwani with Red dupatta',price:'21,500'},
    { id:5,image:'https://drive.google.com/uc?export=view&id=1_x4X1Th92N1g-yUOvbe3Kb7KSt0dWI1Q',category:"Dhorti Serwani",  name:'Art Slik Indo Western Serwani',price:'18,500'},    
    { id:6,image:'https://drive.google.com/uc?export=view&id=1WG_kGvLfCfeVvTD7mT6KJalSD-WxTBmC',category:"Dhorti Serwani",  name:'Slik Golden Browern Dhorti Serwani',price:'21,500' },
    { id:7,image:'https://drive.google.com/uc?export=view&id=1qHGSvyytQzqv_lNOUdB0Z7FuMseR7MFe',category:"Serwani",name:'Light Green Straight Serwani Set',price:'17,550'},    
    { id:8,image:'https://drive.google.com/uc?export=view&id=1iB8WCVYtWh1xAdYjx_BMyhUuIcnUViKu',category:"Kurta",name:'Green Printed semi Indo Western Kurta set',price:'17,500'},    
    { id:9,image:'https://drive.google.com/uc?export=view&id=1_nEO_m0M1M590HrU7vHqAwvGar4VS9jm',category:"Kurta",name:'Pure White Western Style Kurta Set',price:'18,000'},    
    { id:10,image:'https://drive.google.com/uc?export=view&id=1CVkfR6M3mLcl3zXReqyTmfgPV88nNd_p', category:"Dhorti Serwani",   name:'Gray and Black Dhorti Serwani',  price:'15,500 '},
     
]
const Boutique_Products=[

                //     anarkali 
    { id:"1", images:'https://drive.google.com/uc?export=view&id=1IDUTrqjgFMPayo1gTJqrfjOkza3sHwm_',name:'Green Color & Embroider with Web Anarkali Gown',price:'15000', categroies:"Anarkali" },
    { id:"2", images:'https://drive.google.com/uc?export=view&id=1GH4FWA2f5pSbORwP6gF58lsub8kXngld',name:'Dark Green with Embroider Anarkali Gown',price:'15499',categroies:"Anarkali" },
    { id:"3", images:'https://drive.google.com/uc?export=view&id=1j1iuAkEbPoa53v3qhZudXv3udlcwOyAp',name:'Stunning Red Anarkali Gown',price:'25500',categroies:"Anarkali" },
    { id:"4", images:'https://drive.google.com/uc?export=view&id=16ieuTZ6SlPPtr32OV8C_pJ-C0UITYQWM',name:'Pink Anarkali Gown for Bride',price:'17500',categroies:"Anarkali" },
    { id:"5", images:'https://drive.google.com/uc?export=view&id=1JAflBpXsxp_XNlTq_3Rvdh2uFPMOIx28',name:'Pink Anarkali Gown with Dupatta',price:'15000',categroies:"Anarkali" },
    { id:"6", images:'https://drive.google.com/uc?export=view&id=16uIt4t5SkFc0KYwcZVpZTfYEbS_MxCC2',name:'Peach Net Heavy Embroidered Wedding Anarkali Gown',price:'32000',categroies:"Anarkali" },
    { id:"7", images:'https://drive.google.com/uc?export=view&id=1d-ftuCqbN29eKdeOdti0aCON850e5m0I',name:'Maroon Anarkali suits with Heavy Embroidery Gown',price:'40000',categroies:"Anarkali" },
    { id:"8", images:'https://drive.google.com/uc?export=view&id=1q3X_kg6HnCi_6i3SijrwZMQvYpTnyRsq',name:'Stunning Green Anarkali Gown',price:'35675',categroies:"Anarkali" },
    { id:"9", images:'https://drive.google.com/uc?export=view&id=1lxR6gY4XXeFN3dHpaVtN2iEoM088XnS9',name:'Red Heavy Web Anarkali Gown ',price:'21000',categroies:"Anarkali" },
    { id:"10", images:'https://drive.google.com/uc?export=view&id=1ViPrzOJqSKBuWtPIFTIEXcDeenazXq4o',name:'Green Heavy Web Anarkali Gown',price:'21500',categroies:"Anarkali" },
    { id:"11", images:'https://drive.google.com/uc?export=view&id=1WqU-OXTvud28Yztk9afKKn9sBUQl2BFx',name:'Dark Pink Heavy Web Anarkali Gown',price:'21550',categroies:"Anarkali" },
    { id:"12", images:'https://drive.google.com/uc?export=view&id=1L-v7s6YLj_4e3qKhZHP_SX6jugbsCdGr',name:'Stunning heavy Embroider Pink Anarkali Gown',price:'29999',categroies:"Anarkali" },
    { id:"13", images:'https://drive.google.com/uc?export=view&id=1DQWYBN_XBNJ1iitM9wEfN0Yi34_nJ9sy',name:'Stunning heavy Embroider Yellow Anarkali Gown with Web Dupatta',price:'25000',categroies:"Anarkali" },
    { id:"14", images:'https://drive.google.com/uc?export=view&id=1F8wVioqMUhh6hph4_P7zi4bEElN1diJc',name:'Green Anarkali Gown for Bride  Wedding',price:'24000',categroies:"Anarkali" },
    { id:"15", images:'https://drive.google.com/uc?export=view&id=12GW5tAxztLv44kJxP3wCAe3arziBxjIX',name:'Yellow Anarkali Gown with Pink Dupatta',price:'27450',categroies:"Anarkali" },
    { id:"16", images:'https://drive.google.com/uc?export=view&id=12tbL7VmAkPmYb5huLLokfIqKDNC4dN8r',name:'Heavy Embroider Red Anarkali Gown',price:'20000',categroies:"Anarkali" },
    { id:"17", images:'https://drive.google.com/uc?export=view&id=1l0Bpwvbw5NLyj85pzon3eFiQ4svoxEyN',name:'Light Green Anarkali Gown',price:'19000',categroies:"Anarkali" },
    { id:"18", images:'https://drive.google.com/uc?export=view&id=19NGFTtvIBRx5vtUCDkoYwRIqU6xT1oRv',name:'Flowers Embroidery with Anarkali Gown',price:'23000',categroies:"Anarkali" },
    { id:"19", images:'https://drive.google.com/uc?export=view&id=1tNQmTIycHzfnEHrPSGgYory6M9WB6W2O',name:'White Anarkali Gown',price:'24500',categroies:"Anarkali" },
    { id:"20", images:'https://drive.google.com/uc?export=view&id=1v678EN46LDNQ22FXi85HYnsx-rhFpNSe',name:'Red Anarkali Gown for Bride',price:'24800',categroies:"Anarkali" },
    { id:"21", images:'https://drive.google.com/uc?export=view&id=1BCdC5neT0f6stFsS-achKNpABFiLudY6',name:'Dark Purpule Anarkali Gown for Bride',price:'23700',categroies:"Anarkali" },
    { id:"22", images:'https://drive.google.com/uc?export=view&id=1JfVOsAfUgAJVUKMqlToYdbvhlhBH2xf4',name:'Anarkali Gown with Red Net Dupatta',price:'15000',categroies:"Anarkali" },
    { id:"23", images:'https://drive.google.com/uc?export=view&id=1mDmv3eVW5WIsX8GhNX67CS5WsINSMdiQ',name:'Stunning Heavy Embroidery Red Anarkali Gown',price:'35000',categroies:"Anarkali" },
                    //  pattu sarees
    {  id:"24",images:'https://drive.google.com/uc?export=view&id=1ri6EvHtxAOdiR7PsPAfKi9uQWkf2pGor',name:'Green Saree with Red Border',price:'5000',categroies:"PattuSaree" },
    {  id:"25",images:'https://drive.google.com/uc?export=view&id=1Rc9XnUaEMnZTUgY6-CtsCBOnBL0utMxI',name:'Stunning Gold with Maroon Pattu Saree',price:'5500',categroies:"PattuSaree" },
    {  id:"26",images:'https://drive.google.com/uc?export=view&id=1werKmW1YohieitzOvQ-YlPzHa8KFssTw',name:'BrownRed with Gold Coding Pattu Saree',price:'4500',categroies:"PattuSaree" },
    {  id:"27",images:'https://drive.google.com/uc?export=view&id=1I9fjp-BTfhQg3bpgo9C18S6Up3E5QmuG',name:'Dark Blue Kanchipuram Pattu Saree',price:'6500',categroies:"PattuSaree" },
    {  id:"28",images:'https://drive.google.com/uc?export=view&id=1oB7K0Ik9ZkbVaWCwPgV0hRpypRAaj3w_',name:'Yellow Pattu Saree',price:'5000',categroies:"PattuSaree" },
    {  id:"29",images:'https://drive.google.com/uc?export=view&id=1cF5xGJ46W02XGpNIgEij5FRGViCnHBtU',name:'Peacock Green Pattu Saree',price:'4500',categroies:"PattuSaree" },
    {  id:"30",images:'https://drive.google.com/uc?export=view&id=1oZCGR97QO2bkt_5oaU7JV1vya6rgg-Z5',name:'Parrot Green Pattu Saree',price:'4950',categroies:"PattuSaree" },
    {  id:"31",images:'https://drive.google.com/uc?export=view&id=1JeRmS51eLZE0Rhvi8WwCuwypoaGb4vja',name:'Pink with Flowers Coding Pattu Saree',price:'7500',categroies:"PattuSaree" },
    {  id:"32",images:'https://drive.google.com/uc?export=view&id=1cjHBtCSVlzYmuTeYC1B5SNlDQlVYgApb',name:'Green Pattu Saree',price:'6500',categroies:"PattuSaree" },
    {  id:"33",images:'https://drive.google.com/uc?export=view&id=1JswhJNPhu2z5SRne6jGsxE6TJZt6vIL-',name:'Gray with purple border Pattu Saree',price:'6750',categroies:"PattuSaree" },
    // sarees
    { id:"34", images:'https://drive.google.com/uc?export=view&id=1N0qLS1F9wFOsmUuZecKeMQwvBsy0gOoc',name:'Pink Saree for Bride',price:'10000',categroies:"Saree"},
    { id:"35", images:'https://drive.google.com/uc?export=view&id=1Eol41I4Fy85EvaJpyPJLoRnivSEdOvDB',name:'White with Flower Decoration Saree',price:'12000',categroies:"Saree"},
    { id:"36", images:'https://drive.google.com/uc?export=view&id=1bEk7KyNFMnEJ0K0joNFbk-RiWs3rA1--',name:"Women's Art Slik Saree",price:'12500',categroies:"Saree"},
    { id:"37", images:'https://drive.google.com/uc?export=view&id=15kaVVrpiyFGVlk1pBNxN_cBNunxI8FtG',name:'Purple with Green & Gold Border Saree',price:'8500',categroies:"Saree"},
    { id:"38", images:'https://drive.google.com/uc?export=view&id=1K2bdC02dzgFdNop8GsIiGVesq2vLUZI4',name:'Green & Meroon color with Flower Embroider Saree',price:'9500',categroies:"Saree"},
    { id:"39", images:'https://drive.google.com/uc?export=view&id=1fZLyEzZYzPEYKroD6a0douW-kAxM4p3N',name:'Stunning Yellow & Red color Slik Saree',price:'10000',categroies:"Saree"},
    { id:"40", images:'https://drive.google.com/uc?export=view&id=1jxAy7duSzMngngCLLCa0MK4qFtNMSBjK',name:'Maroon color SLik Saree',price:'5000',categroies:"Saree"},
    { id:"41", images:'https://drive.google.com/uc?export=view&id=1luU55gwtPJNJkHhpn_FUcaY488CcZqS7',name:'Green Slik Saree',price:'4000',categroies:"Saree"},
    { id:"42", images:'https://drive.google.com/uc?export=view&id=1xerR9lmNaAfkz42fEPGXt9S8gx-q-VaX',name:'Purple with Gold Slik Saree',price:'7500',categroies:"Saree"},
    { id:"43", images:'https://drive.google.com/uc?export=view&id=1GmOy8esA-fT0_Zj2XHrWLKLlgfE6eZN8',name:'Sky Blue Slik Saree ',price:'7550',categroies:"Saree"},
    { id:"44", images:'https://drive.google.com/uc?export=view&id=1kKbIOU1H9mkeNA5WCnrIxjFW3HNmG5sp',name:'Red with Gold Slik Saree',price:'8500',categroies:"Saree" },
    { id:"45", images:'https://drive.google.com/uc?export=view&id=1bwngngTP4IZYi-3M695bAelTbo4EROiC',name:'Red & Gold Full Slik Saree',price:'6500',categroies:"Saree" },
    { id:"46", images:'https://drive.google.com/uc?export=view&id=1tUpBQCgLHAKY4zI3NnIyVj-jbD-qj7RW',name:'Mango Yellow Slik Saree',price:'7500',categroies:"Saree" },
    { id:"47", images:'https://drive.google.com/uc?export=view&id=1h9L_DqnuYf3LQVmcSbNLtiRxEJvWTEJl',name:'Pink Floral Embroidered Net Saree',price:'8500',categroies:"Saree" },
    { id:"48", images:'https://drive.google.com/uc?export=view&id=1un-_1bREDxHRQ1w_91Ik5MLlhYMDPoYF',name:'Mango color Slik Saree',price:'9500',categroies:"Saree" },
    { id:"49", images:'https://drive.google.com/uc?export=view&id=1SYkmIU3l2qP-HGZRG8atZSt4L1pRwGmo',name:'Dark Blue Saree with Mango designs',price:'12000',categroies:"Saree" },
    { id:"50", images:'https://drive.google.com/uc?export=view&id=1U4Mz3uTQF1CEOWjB9nrapKX6Cl5XXwxl',name:'Purple Saree with Mango designs',price:'12500',categroies:"Saree" },
    { id:"51", images:'https://drive.google.com/uc?export=view&id=1ozsHdYEgWwzi_y7dPJMFz0-ZDdeFXQB4',name:'Peacock Green color slik saree',price:'13000',categroies:"Saree" },
    { id:"52", images:'https://drive.google.com/uc?export=view&id=1q6k_7-9VDC1EDt-OWg-gKt-9ytUoysuS',name:'Yellow with Mango slik Saree',price:'7500',categroies:"Saree" },
    { id:"53", images:'https://drive.google.com/uc?export=view&id=1O4EqlHfNn-vIN0_YRqvLbMg7sVQ2LdJH',name:'Red Slik Saree',price:'8650',categroies:"Saree" },
    { id:"54", images:'https://drive.google.com/uc?export=view&id=1PJKW42doF8a11oT8teZepJPON_2IeUd6',name:'Dark Green orange Border Slik Saree',price:'8500',categroies:"Saree" },
    { id:"55", images:'https://drive.google.com/uc?export=view&id=16t5sKyi4xlcZJWVQAOFvvQxtrr3Y8M15',name:'Maroon Slik Saree',price:'7500',categroies:"Saree" },
         // anarkali serwani
    { id:"56", images:'https://drive.google.com/uc?export=view&id=1oa9c6Xd3deLwmWQqaN_GhqFMOrsyfBTE',name:'White Anarkali Saree for Groom',price:'15000',categroies:"Anarkali_Serwani" },
    { id:"57", images:'https://drive.google.com/uc?export=view&id=1Y5Hbi5G59sban47QVCrbNo5S1M08Ct96',name:'Pink Slik Anarkali Serwani with ',price:'16000',categroies:"Anarkali_Serwani" },
    { id:"58", images:'https://drive.google.com/uc?export=view&id=1pLo6YtKy8OCHw91BO1SY1DunIhKKbx23',name:'Pink Slik Anarkali Serwani',price:'14500',categroies:"Anarkali_Serwani" },
    { id:"59", images:'https://drive.google.com/uc?export=view&id=1vyf7tCQfXJiGW1_M3iRO_6cRiqcQG6Zd',name:'Slik Anarkali Serwani with Green Dupatta',price:'21000',categroies:"Anarkali_Serwani" },
    { id:"60", images:'https://drive.google.com/uc?export=view&id=1R4vL36VCZSVDJHlASvU1Jnxd7i4ByeGF',name:'Slik Anarkali serwani with Red dupatta',price:'21500',categroies:"Anarkali_Serwani" }, 
    { id:"61", images:'https://drive.google.com/uc?export=view&id=1Z_iKcP6JwX4dIfvwgm589rweRnG_VdMJ',name:'Slik Anarkali serwani with Red Dupatta & Chain',price:'21000',categroies:"Anarkali_Serwani" },
    { id:"62", images:'https://drive.google.com/uc?export=view&id=18JO2GNNMx_yWUjQlzuw6vp2c-LgFS2Lx',name:'Wedding Serwani for Groom',price:'14500',categroies:"Anarkali_Serwani" },
    { id:"63", images:'https://drive.google.com/uc?export=view&id=1_WLdEVY_r4aw6UCZqlHE9cxqvtCVyyTv',name:'White Sequence work Serwani for Groom',price:'15999',categroies:"Anarkali_Serwani" },
    { id:"64", images:'https://drive.google.com/uc?export=view&id=1EhDlRZR7EyhkhBEene6d9BfT3L7CRUic',name:'Pink Serwani for Wedding',price:'17450',categroies:"Anarkali_Serwani" },
    { id:"65", images:'https://drive.google.com/uc?export=view&id=1tUpGA_ADF8CEPtZ983kcCU4mgAySNq2L',name:'Red Wedding Anarkali for Wedding',price:'19999',categroies:"Anarkali_Serwani" },
    { id:"66", images:'https://drive.google.com/uc?export=view&id=1HvwRNIbXxpj5O6R7a8SPL1YFJGY3DNcd',name:'Gorgeous Pink Wedding Anarkali Serwani for Wedding Groom',price:'16590',categroies:"Anarkali_Serwani" },
    { id:"67", images:'https://drive.google.com/uc?export=view&id=10Wn3vgYMrkjXYHXFj6WI1ziomd4Viec7',name:'Sequences work for Anakali Serwani with Chain',price:'15490',categroies:"Anarkali_Serwani" },
    { id:"68", images:'https://drive.google.com/uc?export=view&id=1vW3sESS_MATJEY-BNn63qmFP2WUJqXCW',name:'Pure White Anarkali Serwani',price:'13500',categroies:"Anarkali_Serwani" },
    { id:"69", images:'https://drive.google.com/uc?export=view&id=1UnpTZJ3s95ocqsc95mc0ltQMmz7YKAYb',name:'White with Flower Embroidered Serwani for Groom',price:'22450',categroies:"Anarkali_Serwani" },
    // Dhoti serwani
    {  id:"70",images:'https://drive.google.com/uc?export=view&id=1G7aixB4K_IP4iRitraefiiZYx38n9InO',name:'Pure White & Emboridered Dhorti Serwani',price:'18570',categroies:"Dhorti_Serwani"},    
    {  id:"71",images:'https://drive.google.com/uc?export=view&id=1zzmx6d-AMu9UeyaNnMBt5-mA6n-Mdrws',name:'Gold and Maroon Pant with Duppatta Dhorti Serwani',price:'16800',categroies:"Dhorti_Serwani"},    
    {  id:"72",images:'https://drive.google.com/uc?export=view&id=1CVkfR6M3mLcl3zXReqyTmfgPV88nNd_p',name:'Gray and Black Dhorti Serwani',price:'15500',categroies:"Dhorti_Serwani"},    
    {  id:"73",images:'https://drive.google.com/uc?export=view&id=1x4CPSr9LzDKaJuhr_ThnVnM24f9radIa',name:'Shandol Slik Dhorti Serwani',price:'13000',categroies:"Dhorti_Serwani"},    
    {  id:"74",images:'https://drive.google.com/uc?export=view&id=1qdSOrkE2DXodkn2UQgXZqbtIOoSnin33',name:'Peacock Slik Dhorti Serwani ',price:'14950',categroies:"Dhorti_Serwani"},    
    {  id:"75",images:'https://drive.google.com/uc?export=view&id=1TPx0RXNA2CXdV_C_qtbjvls7g2O3bXdR',name:'Flower decoration With Black Dhorti Serwani ',price:'18999',categroies:"Dhorti_Serwani"},    
    {  id:"76",images:'https://drive.google.com/uc?export=view&id=1_x4X1Th92N1g-yUOvbe3Kb7KSt0dWI1Q',name:'Art Slik Indo Western Serwani',price:'18500',categroies:"Dhorti_Serwani"},    
    {  id:"77",images:'https://drive.google.com/uc?export=view&id=1WG_kGvLfCfeVvTD7mT6KJalSD-WxTBmC',name:'Slik Golden Browern Dhorti Serwani',price:'21500',categroies:"Dhorti_Serwani"},    
    {  id:"78",images:'https://drive.google.com/uc?export=view&id=1-b2Th2MrS7YCPFWSi_ltgh8Q57xTKixs',name:'White & black Border Dhorti Serwani',price:'15550',categroies:"Dhorti_Serwani"},    
    {  id:"79",images:'https://drive.google.com/uc?export=view&id=1_SfhmS5r8wBprqBMV-snWvfptOneiblW',name:'Pink Serwani and Goldenbrown Dhorti for Groom',price:'14800',categroies:"Dhorti_Serwani"},    
    {  id:"80",images:'https://drive.google.com/uc?export=view&id=1xvqfzHULLVbEeRxwC8FrIyraWFMO072w',name:'Shadal and White combination Dhorti Serwani',price:'13500',categroies:"Dhorti_Serwani"},    
    {  id:"81",images:'https://drive.google.com/uc?export=view&id=1u7Pj3fH_EL6LfN82ayDy_B9XH7I_tsOw',name:'Stunning Look of Red And Shadal Dhorti Serwani',price:'18500',categroies:"Dhorti_Serwani"},    
// jodhpuri suits
    { id:"82", images:'https://drive.google.com/uc?export=view&id=1RAd38CbDKgbuh43adXo2GnmNL2d8mUtD',name:'Black JOdhpuri Suit for Wedding - 1',price:'8500',categroies:"Jodhpuri_Suits"},    
    { id:"83", images:'https://drive.google.com/uc?export=view&id=18EXgw4d-C1V1uhNJO9s8LZg1V_VqEeDz',name:'Gray Blue Jodhpuri Suit for Wedding',price:'7599',categroies:"Jodhpuri_Suits"},    
    { id:"84", images:'https://drive.google.com/uc?export=view&id=1PUGcwGh5IBW66UNrziElXx-cqJ2Zq5qv',name:'Pure Black Jodhpuri Suit -2',price:'7999',categroies:"Jodhpuri_Suits"},    
    { id:"85", images:'https://drive.google.com/uc?export=view&id=1Lfmq1EyydXY3wgUbW2LFiVwUnVzZ2lPS',name:'Light Green & Shadal Combination for jodhpuri Suit',price:'10000',categroies:"Jodhpuri_Suits"},    
    { id:"86", images:'https://drive.google.com/uc?export=view&id=1tbFKO_cqXiLCNO-NmWcFOmb2Mzbz2EVK',name:'Gray Blue with Heavy Embroridery Suits',price:'8500',categroies:"Jodhpuri_Suits"},    
    { id:"87", images:'https://drive.google.com/uc?export=view&id=1K5jDo_WhQB-p3pa9fdNgDXbJLvpdgmIp',name:'Navy Blue Jodhpuri Suits',price:'9999',categroies:"Jodhpuri_Suits"},    
    // kurta
    {  id:"88",images:'https://drive.google.com/uc?export=view&id=1MuQ3u_A27Ey4q-HRIufJrbj__0pe_zR-',name:'Pure White Kurta for Groom',price:'9500',categroies:"Kurta"},    
    {  id:"89",images:'https://drive.google.com/uc?export=view&id=19OmKPz_nnkVLLfVZp73LoOFIn4YemunH',name:'Black and While Combination Kurta',price:'7500',categroies:"Kurta"},    
    {  id:"90",images:'https://drive.google.com/uc?export=view&id=1W6RygyttXtssjOY9Unvuq4rS1hp6L40S',name:'Light Blue with Flower Decoration Kurta',price:'7550',categroies:"Kurta"},    
    {  id:"91",images:'https://drive.google.com/uc?export=view&id=1rI1Mjc77_w73QlN8qmuL1DU1ZO-zj4JS',name:'White and Black Kurta Combination',price:'6500',categroies:"Kurta"},    
    {  id:"92",images:'https://drive.google.com/uc?export=view&id=1KSKeaAC0_0B0u1IowQ7F6p6M-r7qhK1o',name:'Men Solid Straight Kurta',price:'6000',categroies:"Kurta"},    
    {  id:"93",images:'https://drive.google.com/uc?export=view&id=1pyDoBARoeqKIm4FppVcthqqcw-afMbI-',name:'Slik Embroidered Kurta in Sandal with Dupatta',price:'13590',categroies:"Kurta"},    
    {  id:"94",images:'https://drive.google.com/uc?export=view&id=1cLGbxppOrvUsKtkJJ0dBZya62qcYj70r',name:'Pink kurta with Slik Embroidered',price:'14500',categroies:"Kurta"},    
    {  id:"95",images:'https://drive.google.com/uc?export=view&id=1iB8WCVYtWh1xAdYjx_BMyhUuIcnUViKu',name:'Green Printed semi Indo Western Kurta set',price:'17500',categroies:"Kurta"},    
    {  id:"96",images:'https://drive.google.com/uc?export=view&id=1_nEO_m0M1M590HrU7vHqAwvGar4VS9jm',name:'Pure White Western Style Kurta Set',price:'18000',categroies:"Kurta"},    
    {  id:"97",images:'https://drive.google.com/uc?export=view&id=1_ASUKy2R5dICJqH_S-8bf3yKgcghylwt',name:'Pure White Straight Kurta Set',price:'6999',categroies:"Kurta"},    
    {  id:"98",images:'https://drive.google.com/uc?export=view&id=1mhERbJMYqpqZiukCftPqjprPXJMgW93v',name:'Green & White Flower Printed Kurta Set',price:'6950',categroies:"Kurta"},  
            // serwani
    {  id:"99", images:'https://drive.google.com/uc?export=view&id=1ZBBOXDVf5a0j1srN8pLz8PTRuluekGoo',name:'Gold & Red Combined Floral Patterned Serwani Set',price:'21599',categroies:"Serwani"},    
    {  id:"100",images:'https://drive.google.com/uc?export=view&id=1U_OqitbWrsUkxKYk4jm21DAjDKdex-h3',name:'Cherry Blossom Pink Floral Patterned Serwani Set',price:'19599',categroies:"Serwani"},    
    {  id:"101",images:'https://drive.google.com/uc?export=view&id=1qtD2iiH5tnnrOLxVMoGAAy2PNxGsTKO4',name:'Slik With Heavy Embroidered Serwani Set',price:'22999',categroies:"Serwani"},    
    {  id:"102",images:'https://drive.google.com/uc?export=view&id=1qHGSvyytQzqv_lNOUdB0Z7FuMseR7MFe',name:'Light Green Straight Serwani Set',price:'17550',categroies:"Serwani"},    
    {  id:"103",images:'https://drive.google.com/uc?export=view&id=1pZ8cjMmgWJPnl7Fawyx8EGxumdVKvjeb',name:'Blue & FLower Pattern Serwani Set',price:'18000',categroies:"Serwani"},    
    {  id:"104",images:'https://drive.google.com/uc?export=view&id=16oW3kYOfrjmsY8fInKfDKttbe4uUeFVT',name:'Royal Gold & Sandal Look Serwani Set',price:'19999',categroies:"Serwani"},    
    {  id:"105",images:'https://drive.google.com/uc?export=view&id=1yuWIvIw1EDExHA9_UbQH6jDMNRY7jIIf',name:'Pearl White with Semi Indo Western Serwani',price:'21590',categroies:"Serwani"},    
    {  id:"106",images:'https://drive.google.com/uc?export=view&id=1fTNd1T2c308xsW_RkIbrIBN-3rsUO-jP',name:'Peacock Color with Embroidered Serwani Set',price:'22500',categroies:"Serwani"},    
    {  id:"107",images:'https://drive.google.com/uc?export=view&id=1DmYf8Y2JtZPfTGt5kroYDbOkS3WtcH0a',name:'Gold and Sandal with Chikankari Serwani Set ',price:'17800',categroies:"Serwani"},       
    {  id:"108",images:'https://drive.google.com/uc?export=view&id=1MlKVgM8MDbTiofJroyGMTOb7bSfUoFXD',name:'Black & Flower Printed Coat Model Serwani',price:'18999',categroies:"Serwani"},    
    {  id:"109",images:'https://drive.google.com/uc?export=view&id=1kb-G41bFA5FCBJTBBZw0CBLXG1H9RmTj',name:'Black & White Combined Serwani Set',price:'14499',categroies:"Serwani"},      
]

export {Bride_collections,Shoe_collections,Groom_collections,Top_categories,Boutique_Products};
